### ISSUE TITLE
Run ESLint on dotfiles

### ISSUE THREAD

**Issue by jdbruijn** [wagoid/commitlint-github-action#100]
I noticed invalid code in the lintstaged configuration file, which wasn't picked up by ESLint. ESLint doesn't do this by default, see eslint/eslint#10341. I suggest creating a `.eslintignore` file like I use in [`vidavidorra/repo-template`](https://github.com/vidavidorra/repo-template/blob/main/.eslintignore). The final `!.*` enables it to run on dotfiles. Currently we (ab)use the `.gitignore` file for ESLint too, but we can't just add `!.*` to the gitignore as that will stop ignoring some dotfiles we don't want.

**Comment by wagoid** [comment]
Interesting, didn't know about that default. Sure thing, let's add a separate `.eslintignore` file to make sure those are linted too :rocket:
