### ISSUE TITLE
Action does not look at PR title

### ISSUE THREAD

**Issue by RossThomson** [wagoid/commitlint-github-action#190]
I really like this action you created and wondering if it could be further improved to check the PR title?
I believe this can be accessed through `github.event.pull_request.title` ? Maybe we could have this value passed into your action?

**Comment by wagoid** [comment]
Hey @RossThomson ! There's another action called [Pull request linter](https://github.com/marketplace/actions/pull-request-linter-action) which does this. Would that work for you?

**Comment by RossThomson** [comment]
> Hey @RossThomson ! There's another action called [Pull request linter](https://github.com/marketplace/actions/pull-request-linter-action) which does this. Would that work for you?

Thanks @wagoid that's exactly what I need!
