### ISSUE TITLE
Change of config file for v4?

### ISSUE THREAD

**Issue by browniebroke** [wagoid/commitlint-github-action#194]
I received a bunch of PRs on my repos for the newly released v4 and they mostly [fail the build](https://github.com/browniebroke/django-codemod/pull/435/checks?check_run_id=3075376383#step:4:10). Looking at [the recent changes](https://github.com/wagoid/commitlint-github-action/commit/5463926c07584c419d865a3fc9efdb382be54995), it looks like the config file should be rename from `commitlint.config.js → commitlint.config.cjs`, is that correct?

If so, I guess the [`configFile` option](https://github.com/wagoid/commitlint-github-action#configfile) should be updated accordingly, both its default value and in the README.

Am I missing something? Don't think there is a good way to keep the same file name by looking at [commitlint.js docs](https://commitlint.js.org/#/reference-configuration).

**Comment by wagoid** [comment]
Hey @browniebroke! Yes you're right, sorry for not updating this as part of the breaking changes of v4. I'll Update the default value and the recommended value on README.

>Am I missing something? Don't think there is a good way to keep the same file name by looking at commitlint.js docs.
Yeah, renaming seems to be the only option :/

**Comment by wagoid** [comment]
I've just merged this PR updating README and default config files: https://github.com/wagoid/commitlint-github-action/pull/195
Also updated the `CHANGELOG` of v4 to include this breaking change.

But I won't close this issue yet as I think this is breaking change is too big. I'll update the project to transpile the code, so I won't need to rely on Node.js default resolution logic anymore and we can switch back to allow `.js` extension like commitlint does.

**Comment by wagoid** [comment]
Done! Fixed on [v4.0.3](https://github.com/wagoid/commitlint-github-action/blob/master/CHANGELOG.md#403-2021-07-17)
