### ISSUE TITLE
Consider actor when linting messages

### ISSUE THREAD

**Issue by nandi95** [wagoid/commitlint-github-action#233]
This isn't really an issue with this action (I don't think), I just don't know a better place to start the conversation.

In my repo when dependabot opens a PR sometimes this action fails as the message is over 100 characters.
Is there/can we devise a way so when certain actors make the commit, they're exempt from some rules?

Perhaps this action could somehow pass along some arguments that can be accessed in the config?

**Comment by jdbruijn** [comment]
The actor is not available in the commitlint parsed commit so this would very difficult that way as far as I'm aware. You could however use the commit message type (e.g. `deps`) that tools like Dependabot uses. Then you can use my plugin: https://github.com/vidavidorra/commitlint-plugin-function-rules to selectively allow longer messages. That is exactly what I've implemented in my shared https://github.com/vidavidorra/commitlint-config, so I'd suggest using that or looking at the specified rules there for i.a. Dependabot.
Hope this helps, feel free to use the discussions in either one of those repo's for further questions.
