### ISSUE TITLE
feature request: don't fail on warnings

### ISSUE THREAD

**Issue by topocount** [wagoid/commitlint-github-action#24]
If a rule is configured as a warning if it fails, the linter should still pass in CI. This is the eslint convention, for example

**Comment by wagoid** [comment]
Hi @topocount, thanks for that! I had a look at commitlint CLI and it doesn't fail on warnings. So I'm updating this as a fix, since I should have followed this CLI's behavior from start :rocket:

**Comment by wagoid** [comment]
Fixed in #25 (I linked the PR to itself instead of linking to this issue so it didn't close automatically)

**Comment by topocount** [comment]
Thanks a bunch!
