### ISSUE TITLE
Support for Private Registries

### ISSUE THREAD

**Issue by hitmands** [wagoid/commitlint-github-action#27]
How could I get this action to install our own commitlint config from our own registry?

Thank You!

**Comment by wagoid** [comment]
Hi @hitmands! Currently there's no support for that. I was waiting for this case to appear before adding this feature (you can see more info about that [here](https://github.com/wagoid/commitlint-github-action/blob/601b4ff6812d289eea913dbd6f0fc85981664d46/README.md#about-extends-in-your-config-file)).

I will create a PR to cover that case. It will require another step from you. Will be basically about adding a `NODE_PATH` so I can read modules from it :rocket:

**Comment by wagoid** [comment]
@hitmands done! You can see how to include extra dependencies [In this section of the readme](https://github.com/wagoid/commitlint-github-action/blob/a2c91577420affbed92d248ffc858e65d3979375/README.md#about-extends-in-your-config-file).
