### ISSUE TITLE
Add outputs

### ISSUE THREAD

**Issue by SamMousa** [wagoid/commitlint-github-action#274]
It would be really nice to have some github action outputs for use in other steps.
For example having an output that indicates whether a release will follow, and what type would allow for easy chaining of an action that adds a label to the PR.

**Comment by wagoid** [comment]
Hey @SamMousa! This action adds outputs about all commits that got linted, but we can't create outputs for release-related information.
For that, you would need a separate action depending on your release workflow. This depends on the tool you use for release and your config.

For example using Semantic Release, [semantic-release-action](https://github.com/cycjimmy/semantic-release-action) could help you. You can pass the `dry_run` parameter and check the outputs to see what would be the next release for example.

I'll close this issue but if you have any other comments let me know 💪
