### ISSUE TITLE
[feature] add option for title-only lint check

### ISSUE THREAD

**Issue by yinonov** [wagoid/commitlint-github-action#301]
some PR strategies squash all commits leaving only the PR title relevant to the default branch merge. therefore following commits (following the PR title) checks are not required as they will not be added to git history.

can there be an option to check only the PR's title?

**Comment by wagoid** [comment]
Hey @yinonov! This action only lints commit messages, but you can do that with the [Pull request name linter](https://github.com/marketplace/actions/pull-request-linter-action) action 💪

**Comment by yinonov** [comment]
thanks! will do
