### ISSUE TITLE
Question: Can this action be used to lint Pull request title ?

### ISSUE THREAD

**Issue by mohanraj-r** [wagoid/commitlint-github-action#32]
I have Squash and Merge turned on for master - thus the pull request titles become the commit messages in master. Can this action be used to lint the Pull request title instead for such cases? Maybe an option to say whether to lint the commit msgs (default), the pull request title in addition to commit msgs or just the pull request title ?

**Comment by wagoid** [comment]
hi @mohanraj-r, thanks for the issue! Sorry for the late response, didn't have time to check this earlier. We can definitely add this option, I'll have a look at it :rocket:

**Comment by wagoid** [comment]
I was having a look at this and found out there's already an action that does that: https://github.com/marketplace/actions/pull-request-linter-action.
So I'm closing this issue since the other action does the trick :rocket:

**Comment by mohanraj-r** [comment]
Thanks I will check that out.
