### ISSUE TITLE
PR check only "title" commit

### ISSUE THREAD

**Issue by asafdl** [wagoid/commitlint-github-action#325]
Hi, is there a way to check only the "top commit" or "title" for a merge commit? it seems unnecessary to make every single commit a in a PR a conventional commit

**Comment by jdbruijn** [comment]
Duplicate of #190.

This action probably won't do that, based on the previous answer on this request: https://github.com/wagoid/commitlint-github-action/issues/190#issuecomment-880505974.

**Comment by jdbruijn** [comment]
Duplicate of #190
