### ISSUE TITLE
How to check if the configFile is being used accordingly

### ISSUE THREAD

**Issue by felipecassiors** [wagoid/commitlint-github-action#33]
I tried to set it to `package.json2` to make it fail but it still passes. I wonder if this action supports the configFile to be `package.json`, see: https://github.com/price-search/api/pull/2

**Comment by wagoid** [comment]
Hey @felipecassiors, the easiest way to test if it's working would be to push an invalid commit. For example a commit message without the type: `some commit without type`. If this passes the action is working :smiley: 
Let me know if that fails

**Comment by felipecassiors** [comment]
Hi,

Thank you for the response :D. What I made was to put a [very different configuration on my commitlint (@commitlint/config-patternplate)](https://github.com/price-search/backend/commit/524752bcec10392af202dbaa36e4a228f90fe2ef#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R79) config and expected it to fail. 

And it failed indeed.

**Comment by felipecassiors** [comment]
I wonder, why do we have to specify the `configFile`? 

I mean, `commitlint` already looks for a valid config in the current workspace.

**Comment by wagoid** [comment]
@felipecassiors TBH it was basically because I didn't know they had this strategy of searching multiple locations when I created the action, so I always pass a `configFile` option to commitlint.
We can definitely improve this action to make `configFile` work just like the CLI does! When I have some time I will have a look at that :rocket:

**Comment by felipecassiors** [comment]
I think this Issue can be considered solved. To make the `configFile` be discovered automatically the way the CLI do is another matter.

**Comment by wagoid** [comment]
Agreed! Closing it.
