### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by jdbruijn** [wagoid/commitlint-github-action#381]
Hi @wagoid 

I was taking care of some Dependabot updates that have been open for a very long time and worked on the dev-deps only as that should have no impact on users. After that wanted to discuss with you about updating the production deps as well. I've merged a couple of dev-deps but the process is quite annoying, trying to outrace the release process and waiting for PR rebases, which resulted in a [release](https://github.com/wagoid/commitlint-github-action/releases/tag/v4.1.10) to be created regardless. So I just wanted to check with you, is it okay if we now try to clear the updates and accept the fact that we might get a bunch of releases? I figured if we do, might be best to just push them through as quickly as possible so users will just get one update to the latest version instead of a bunch of updates.

**Comment by wagoid** [comment]
Hi @jdbruijn! I like the PR @Fdawgs, I think it would already help us a lot right? Although I think we may still need to update our workflow to merge dependabot updates together for changes in `dependencies`

**Comment by jdbruijn** [comment]
Yeah, that already helps. Only thing about that is that if we have `chore(deps)` commit in the same workflow run as a `chore(deps-dev)` commit we won't trigger a release. Probably won't happen that often so might not be a big deal.

**Comment by Fdawgs** [comment]
The workflow could be changed so if the author is `dependabot[bot]` and the PR/commit is `chore(deps-dev)` then it won't release?
Dependabot only ever has a single commit per PR.

**Comment by jdbruijn** [comment]
I think we release on commit in main right? So if we would merge in quick succession it could still not release if we merged dev deps after dev. Not sure what a right solution would be, but as I said I think we can manage like that.

**Comment by wagoid** [comment]
@jdbruijn in that case the first commit would release, and second wouldn't. So all good in that case 😋

**Comment by jdbruijn** [comment]
First wouldn't right, because at that point the main branch would contain newer commits. Or does it still push to the main branch for the release in that case?

**Comment by wagoid** [comment]
Ah true, I forgot that it checks out the branch, not the specific ref of the merge commit.
Then I guess we can just remember about it if we ever want to quickly merge two PRs together. As you mentioned  we can manage it since this scenario doesn't happen very often 🚀
