### ISSUE TITLE
No outputs defined

### ISSUE THREAD

**Issue by incorrupt** [wagoid/commitlint-github-action#39]
It would be great to set the output of this action as a [workflow accessible output](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs) so it can be accessed in subsequent steps.

Example text output:
```
⧗   input: fix:
✖   subject may not be empty [subject-empty]
⚠   type must be sentence-case [type-case]

✖   found 1 problems, 1 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

⧗   input: hello world
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

Example JSON output (can be used with [fromJson()](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson))

```json
[
   {
      "id":"a4060537e328962f6808c1fc0232d0a9c4cf761f",
      "message":"fix:",
      "errors":[
         "subject may not be empty [subject-empty]"
      ],
      "warnings":[
         "type must be sentence-case [type-case]"
      ]
   },
   {
      "id":"cb565dfcca3128380b9b3dc274aedbcae34ce5ca",
      "message":"hello world",
      "errors":[
         "subject may not be empty [subject-empty]",
         "type may not be empty [type-empty]"
      ],
      "warnings":[

      ]
   }
]
```

**Comment by wagoid** [comment]
Hi @incorrupt, thanks for the issue! That would definitely be very useful, I'll have a look at it 😃

**Comment by wagoid** [comment]
@incorrupt Done! you can see documentation of the output in the [readme](https://github.com/wagoid/commitlint-github-action#results) :heavy_check_mark:
