### ISSUE TITLE
Unclear what the output format 

### ISSUE THREAD

**Issue by aranw** [wagoid/commitlint-github-action#518]
I was reading the docs and I found it to be unclear as to whether the output from this action is JSON or formatted text

It would be nice to have the option of both which I'm guessing isn't currently available based on the `action.js` file

**Comment by wagoid** [comment]
Hey @aranw! The action logs the results, and also adds JSON output in the standard format that GitHub Actions expects. You can see more explanation about this behavior here: https://github.com/wagoid/commitlint-github-action#results

**Comment by aranw** [comment]
Yeah I'm hoping to copy the output and add it as a comment on the PR

**Comment by wagoid** [comment]
Hey @aranw ! I forgot to mention, we also have an example of the JSON result being used [here](https://github.com/wagoid/commitlint-github-action/blob/master/.github/workflows/commitlint.yml#L29-L31). I'll close this issue, but feel free to create a new issue or improve documentation if needed 💪
