### ISSUE TITLE
Docker image version not updated for newer releases

### ISSUE THREAD

**Issue by bendavies** [wagoid/commitlint-github-action#532]
Hi,

I noticed that when using version 5 of this action that version 4.1.12 is pulled
<img width="350" alt="image" src="https://user-images.githubusercontent.com/625392/191461705-ff2a46dc-3e1d-47ce-a532-6e72719a8792.png">

It seems that this line was not uddated for all releases after 4.1.12
Should it have been?

https://github.com/wagoid/commitlint-github-action/blob/4caf21aed4a778f940d0b17eb109942ef167bb27/action.yml#L36

Thanks

**Comment by wagoid** [comment]
Hi @bendavies, thanks for catching this! Looks like it was a node version issue, I updated workflows to use v16.5.0 and it now works 🚀
