### ISSUE TITLE
standard-version isn't updating changelog info correctly

### ISSUE THREAD

**Issue by wagoid** [wagoid/commitlint-github-action#54]
On [v2.0.3](https://github.com/wagoid/commitlint-github-action/blob/2d572ed5ea8b369af534fa21eea186a7eef07cda/CHANGELOG.md#203-2020-09-14) for example, it should include the feature `use config-conventional as default config` on the list, but it's not.

**Comment by fredicious** [comment]
could it be that it also doesn't bump de version according to semVer, https://github.com/wagoid/commitlint-github-action/releases/tag/v2.0.3 should have been a minor release (v2.1.0) no ?

**Comment by wagoid** [comment]
@fredicious true, looks like it's causing that issue too 🔥

**Comment by wagoid** [comment]
Found the issue, we need to pass `fetch-depth: 0` to `actions/checkout` step. We were using the default fetch depth in the release job which was making it download only the merge commit.
