### ISSUE TITLE
"fatal: Invalid revision range" error

### ISSUE THREAD

**Issue by dangreen** [wagoid/commitlint-github-action#598]
Hi.

Recently, I started to receive this error in the CI of my projects:

https://github.com/TrigenSoftware/simple-release-tools/actions/runs/3558440522/jobs/5977104578

> ```
> error running commitlint
> Command failed with exit code 128: git log --format=%H--------->hash---------%B%n--------->commit--------- 1df333e501eb66ab54c1ba9aa5920e44b73b9314..216c9bf333d2c6bee0abe7ee18d8b9a63a945e8d --first-parent
> fatal: Invalid revision range 1df333e501eb66ab54c1ba9aa5920e44b73b9314..216c9bf333d2c6bee0abe7ee18d8b9a63a945e8d
> Error: Command failed with exit code 128: git log --format=%H--------->hash---------%B%n--------->commit--------- 1df333e501eb66ab54c1ba9aa5920e44b73b9314..216c9bf333d2c6bee0abe7ee18d8b9a63a945e8d --first-parent
> fatal: Invalid revision range 1df333e501eb66ab54c1ba9aa5920e44b73b9314..216c9bf333d2c6bee0abe7ee18d8b9a63a945e8d
>     at makeError (/node_modules/execa/lib/error.js:60:11)
>     at handlePromise (/node_modules/execa/index.js:118:26)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async gitCommits (/run.js:148:7)
>     at async showLintResults (/run.js:301:17)
> ```

Action works perfectly in branches but is broken in the main branch.

**Comment by veged** [comment]
same error here: https://github.com/bem/bem-react/actions/runs/3674496989/jobs/6212783070

**Comment by veged** [comment]
@wagoid

**Comment by simonseyock** [comment]
I ran into the same error, but I noticed that I was not using `fetch-depth: 0` for the checkout action. Setting that solved the issue for me.

**Comment by dangreen** [comment]
@simonseyock @jdbruijn Hi. It works, thanks!
