### ISSUE TITLE
Support push builds?

### ISSUE THREAD

**Issue by ybiquitous** [wagoid/commitlint-github-action#6]
Hi, thanks for the awesome action! 😊 

When I am trying the action, I encounter the following error:

<img width="890" alt="image" src="https://user-images.githubusercontent.com/473530/66791006-3697de00-ef2d-11e9-962e-696657d33afb.png">

https://github.com/ybiquitous/eslint-config-ybiquitous/pull/491/checks?check_run_id=259977307#step:11:7

I want to run commitlint on not only pull request builds but also push builds, so do you have a plan to support push builds?

Here is the YAML file which raises the above error:

https://github.com/ybiquitous/eslint-config-ybiquitous/pull/491/files#diff-fe8421955fd596131bb6f1b78984b2fb

It would be great if you would consider my request.
Thanks.

**Comment by wagoid** [comment]
Hello @ybiquitous, thank you for your feedback! This is indeed a nice use case to cover.
I've just finished adding support for runs on `push` events too in [v1.2.0](https://github.com/wagoid/commitlint-github-action/releases/tag/v1.2.0) :fist_oncoming:

**Comment by ybiquitous** [comment]
@wagoid Thank you for your quick support! The push builds work!

But my PR does not work expectedly... 😢 
https://github.com/ybiquitous/eslint-config-ybiquitous/pull/491

I expect that `commit-github-action` would complain for the commit message "Update test.yml".
My commitlint config is [defined in `package.json`](https://github.com/ybiquitous/eslint-config-ybiquitous/blob/5c6368953fcccd5bf388a91ca1ceb9c98a23ff43/package.json#L114).

On the other hand, `commitlint-travis` works expectedly:
https://travis-ci.org/ybiquitous/eslint-config-ybiquitous/jobs/598540942#L227

**Comment by wagoid** [comment]
@ybiquitous yes, the action supports that too!
You just need to add the `configFile` parameter to the action:
```yaml
with:
  configFile: ./package.json
```
You can see more info about our inputs here: https://github.com/wagoid/commitlint-github-action/blob/master/README.md#configfile
If it still doesn't work let me know!

**Comment by ybiquitous** [comment]
Great! Thank you very much! 😊 👏 👍 

<img width="819" alt="image" src="https://user-images.githubusercontent.com/473530/66924636-ee300b80-f065-11e9-8cba-deaa8fe28de7.png">

**Comment by wagoid** [comment]
Awesome! Glad that it worked 🚀
