### ISSUE TITLE
Check commit messages before committing

### ISSUE THREAD

**Issue by jdbruijn** [wagoid/commitlint-github-action#60]
Working on #59, I've noted that the commit messages are not validated locally during the commit. I had failing commit messages and only found out when the workflow ran on my PR. I think it'd be nice to have it run during the commit as well, with `'commit-msg': 'commitlint -E HUSKY_GIT_PARAMS',` in `husky` hooks for example.

Would you accept PR for this?

One other idea is to run the tests as well before committing, for example using [`lint-staged`](https://github.com/okonet/lint-staged). Would be happy to discuss that here and see your thoughts, and include it in a PR if desired.

**Comment by wagoid** [comment]
Hey @jdbruijn, sure! Would be glad to accept this PR :smiley: 

I agree with both your suggestions, let's go with it :rocket:

**Comment by jdbruijn** [comment]
Cool! I'll be creating separate PR's for that.
