### ISSUE TITLE
Ignore body-max-line-length when dependabot is detected

### ISSUE THREAD

**Issue by felipecrs** [wagoid/commitlint-github-action#69]
This is a follow-up of https://github.com/dependabot/dependabot-core/issues/2445.

I'm just wondering, maybe this action can auto-detect `dependabot` presence and ignore this rule?

**Comment by wagoid** [comment]
Hey @felipecrs! This can be done in the commitlint config. @jdbruijn has come up with a way to do that, you can see it here: https://github.com/wagoid/commitlint-github-action/pull/56#issuecomment-728726419

I'll close this issue, but if you have any other thoughts let me know :fist_oncoming:
