### ISSUE TITLE
Octokit Response Only Returns 30 Commits

### ISSUE THREAD

**Issue by cmitzel-ncino** [wagoid/commitlint-github-action#717]
Hey, it's me again!

The failOnErrors function works awesome - we're able to interact with the results array in another step of the job and make it so that a single passing commit will pass the linter! 

However, there is one small issue. By default, [Octokit only returns a single page of 30 commits](https://github.com/octokit/octokit.js#pagination), so the commit history available to the action is only up to the last 30. It's not a dealbreaker, but I doubt it's intended behavior. I attempted to add the `per_page: 100,` argument to the Octokit call but it broke a number of tests and I'm not sure why, so I figured I'd let you take a look. 

I confirmed that is in fact only returning 30 by making a request to the github api for the PR triggering the action, and confirmed that the API (when given the param `per_page=100`) returned 45 commits, while the results array from the action only returned 30. 

![Screenshot 2023-04-11 at 4 32 09 PM](https://user-images.githubusercontent.com/84025850/231281534-0166f345-54a4-4096-bfe1-377603b17491.png)

![Screenshot 2023-04-11 at 4 32 42 PM](https://user-images.githubusercontent.com/84025850/231281690-f95a6a60-3719-4938-a6a2-44694b26e459.png)

![Screenshot 2023-04-11 at 4 30 56 PM](https://user-images.githubusercontent.com/84025850/231281291-86ced934-45de-4476-b0b4-c81356b9ab86.png)

**Comment by wagoid** [comment]
Hey @cmitzel-ncino! Yeah, I was aware of that limit but didn't bother getting more to wait for people that needed it. We can definitely switch to fetch 100, I'll have a look at it when I have some time 👊

**Comment by cmitzel-ncino** [comment]
No problem! I just wanted to bring it up cause I was losing my mind trying to figure out why my recent commits in my unhinged PR weren't showing up 🤣. As is it works for most repos so I totally get why it isn't a priority, I just wanted to bring it up just in case it's something you'd missed. 😸
