### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by jdbruijn** [wagoid/commitlint-github-action#72]
In #71, breaking changes were introduced, namely removing the action outputs. I think you should very careful with this type of change and should be releasing this with [Semantic Versioning 2.0.0](https://semver.org/) what could be implied based on the used version numbering.

The goal of this issue is merely to inform you about this, and hopefully resulting in careful thought in the future. Feel free to close it once you've read it, and perhaps given your view on it.

With that in mind, the v2.1.7 release should have been v3.0.0 instead, properly informing users and dependency management tools to handle it appropriately. With it now being released as v2.1.7, users will face unexpected issues if they're using the action output.

FYI I'd have been happy to review #71, and pointed it out there, if it weren't merged and released right away.

**Comment by wagoid** [comment]
Hi @jdbruijn, thanks for the catch up! Yes, I follow semver on this action, just forgot about this during this PR. Thanks for prompting to review PRs, will add you to future ones :wink:
