### ISSUE TITLE
Issue with parsing commit message - says subject is empty when it is not

### ISSUE THREAD

**Issue by jbnjohnathan** [wagoid/commitlint-github-action#730]
For this commit I get errors that the subject is empty, and type is empty. But they are not.

Is there an issue when using "." or "-" in the scope?

Using
`wagoid/commitlint-github-action@456526eec71276a59e74aafdfe06a9632ac2eee1 #5.4.1`

```
[commitlint](https://github.com/anzrco/postgres-privx/actions/runs/4860764908/jobs/8664973693#step:4:10)
You have commit messages with errors

⧗   input:  docs(postgres-setup.md): new setup.md file
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

Tested the commit message with https://commitlint.io/ and it says `docs(postgres-setup.md): new setup.md file` is valid

We used 5.3.1 before with the same issue, and upgraded to 5.4.1 to see if it fixed anything but the issue remains.

**Comment by jdbruijn** [comment]
Did you perhaps have a space at the start of the line? Reason is I see `input:  docs ...` (2 spaces behind `input:` and `docs`.

Testing locally `echo 'docs(postgres-setup.md): new setup.md file' | npx commitlint` is valid and `echo ' docs(postgres-setup.md): new setup.md file' | npx commitlint` is invalid. The latter gives same error as what you're describing, so I expect you have a leading space.

```
⧗   input:  docs(postgres-setup.md): new setup.md file
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```
