### ISSUE TITLE
git subtree import

### ISSUE THREAD

**Issue by majg0** [wagoid/commitlint-github-action#743]
Try running a `git subtree add` and make a PR. It will fail because it doesn't have a parent so the `^1` hack doesn't work. Can we do two git logs instead? One including only first commit and second including revision range?

Thanks!

**Comment by wagoid** [comment]
Hi @majg0! I've updated the action to get commits from the event payload or GitHub API, so this shouldn't happen anymore. I'm closing the issue, please let me know if something fails 💪
