### ISSUE TITLE
Upgrade to commitlint 18

### ISSUE THREAD

**Issue by sschuberth** [wagoid/commitlint-github-action#750]
It seem this action to stuck on commitlint 17:

https://github.com/wagoid/commitlint-github-action/blob/6319f54d83768b60acd6fd60e61007ccc583e62f/package.json#L33

However, there's version 18 by now, see https://github.com/conventional-changelog/commitlint/releases. It would be great to get an update to benefit from latest fixes.

**Comment by wagoid** [comment]
Hey @sschuberth! Thanks for the reminder, will update 💪

**Comment by wagoid** [comment]
It's updated! Unfortunately looks like there's an issue in the release setup, it didn't generate a changelog correctly and updated as a patch instead of major. But it should work fine without any changes for most people
