### ISSUE TITLE
feature request: commit list rest endpoint

### ISSUE THREAD

**Issue by braxton-dameron** [wagoid/commitlint-github-action#752]
We use this action on `pull_request` and `push`, but we've noticed a small discrepancy after merging a couple of our branches. Our PRs that have more than 20 commits do not lint every commit. I've realized this is because of a limit on the `push` webhook payload.

> commits array of objects Required
An array of commit objects describing the pushed commits. (Pushed commits are all commits that are included in the compare between the before commit and the after commit.) The array includes a maximum of 20 commits. If necessary, you can use the [Commits API](https://docs.github.com/rest/commits) to fetch additional commits. This limit is applied to timeline events only and isn't applied to webhook deliveries.

https://docs.github.com/en/webhooks/webhook-events-and-payloads#push

Is there interest in supporting the REST endpoint to enable consistent linting on large PRs using something like `octokit.rest.repos.listCommits(...)`? It's atypical for my team to have large PRs like this, but with very active repos and merges it may become more frequent.

https://docs.github.com/en/free-pro-team@latest/rest/commits/commits?apiVersion=2022-11-28#list-commits
https://octokit.github.io/rest.js/v20#repos

**Comment by wagoid** [comment]
I had to revert the previous fix to overcome this issue #799. I'm thinking here now, in your case the `pull_request` runs are linting all commits of the PR, right? Is this actually an issue in the end?

I'm thinking the only issue here would be on force pushes that have more than 20 commits on them, but it feels like an edge case that is safely covered by the `pull_request` run. What do you think?

**Comment by braxton-dameron** [comment]
> I had to revert the previous fix to overcome this issue #799. I'm thinking here now, in your case the `pull_request` runs are linting all commits of the PR, right? Is this actually an issue in the end?
> 
> I'm thinking the only issue here would be on force pushes that have more than 20 commits on them, but it feels like an edge case that is safely covered by the `pull_request` run. What do you think?

@wagoid Ah sorry the change we were implementing caused that issue. Yes on `pull_request` runs we can lint all commits of the PR. It is still an issue when we run the linting process again on `push` after the PR is merged with more than 20 commits on it. It gives us a discrepancy between the semantic release detected before and after merge. It is an edge case, but at scale with the number of repos and engineers we have consuming the action it is noticeable.

**Comment by Brian-Triplett** [comment]
@wagoid I was just plain wrong on my assumption of how `before` worked on `listCommits`. I tested it out locally and it just grabs commits starting with before and going *backwards*.

I found what I think is a better solution and posted it in https://github.com/wagoid/commitlint-github-action/pull/801
