### ISSUE TITLE
BUG: module is not defined in ES module scope

### ISSUE THREAD

**Issue by chemelli74** [wagoid/commitlint-github-action#786]
Upgrade from 5.4.5 to 6.0.1 fails:

https://github.com/chemelli74/fitbit-web-api/actions/runs/8639584968/job/23829212680

**Comment by wagoid** [comment]
This is part of the v6 breaking change, see here how to fix: https://github.com/wagoid/commitlint-github-action/issues/777#issuecomment-2032378406
