### ISSUE TITLE
deps: update @commitlint monrepo

### ISSUE THREAD

**Issue by jdbruijn** [wagoid/commitlint-github-action#97]
@wagoid Regarding the `@commitlint` monorepo update, is it okay for you to update to v12 in one go or do you prefer to update to v11 first separately?

 As you've indicated they're breaking changes for this as well, so I suggest the following commit message.
 
 ```
  fix(deps): udpate commitlint monorepo to v12
  
  BREAKING CHANGES: Remove support for lerna v2 and change the order of the `extends` resolution from right-to-left to left-to-right.  
  ```

**Comment by wagoid** [comment]
Hey @jdbruijn, I'm fine to upgrade to v12 directly. Your commit message looks great to me :star2: :rocket:
