### ISSUE TITLE
Move Husky configuration to .github

### ISSUE THREAD

**Issue by jdbruijn** [wagoid/commitlint-github-action#98]
Husky v5 uses a different configuration and was merged in #83. The configuration should be changed as part of that major update. I suggest moving it to the `.github/husky` directory. We don't need `pinst` as this isn't published.

**Comment by wagoid** [comment]
Completely missed that one, nice catch @jdbruijn! I don't think `.github/husky` would be a good fit, because the `.github` folder is specific to github and husky is just for `git`. What about just keeping in the `.husky` folder as they suggest by default?

**Comment by jdbruijn** [comment]
That'd be fine too, I was just thinking to keep the root somewhat clutter free but no strong opinion on it.
